### ISSUE TITLE
HTML Feedback 

### ISSUE THREAD

**Issue by Enspired** [madisonsinc97/GDMA-2662-Assignment-1#1]
Correcting some HTML feedback provided in class. 

Index 
- [x] is not the h1 (title or headline) for the page  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L36 
- [x] These are in the same directory as the index.html page so no directory navigation "../' is necessary to link to these pages  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L28 
- [x]  these paragraphs will need to be wrapped inside the Li's on the line above. Only LI elements can be direct children of a UL  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L51
- [x] these are not subheads to 'optimized hosting' they should be h2's  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L71 
- [x] since the previous headlines are updated to h2's these will need to be updated to h3's. since the previous headlines are updated to h2's these will need to be updated to h3's. https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L104 
- [x] hyphens do not need to be encoded  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L119 
- [x] be sure href values are spelled correctly to match the content  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L118 

Benefits  / Hosting 
- [x] update title tags on pages to reflect the page you're on  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/benefits.html#L13

**Comment by madisonsinc97** [comment]
> Correcting some HTML feedback provided in class.
> 
> Index
> 
> * [x]  is not the h1 (title or headline) for the page  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L36
> * [x]  These are in the same directory as the index.html page so no directory navigation "../' is necessary to link to these pages  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L28
> * [x]   these paragraphs will need to be wrapped inside the Li's on the line above. Only LI elements can be direct children of a UL  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L51
> * [x]  these are not subheads to 'optimized hosting' they should be h2's  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L71
> * [x]  since the previous headlines are updated to h2's these will need to be updated to h3's. since the previous headlines are updated to h2's these will need to be updated to h3's. https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L104
> * [x]  hyphens do not need to be encoded  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L119
> * [x]  be sure href values are spelled correctly to match the content  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/index.html#L118
> 
> Benefits / Hosting
> 
> * [x]  update title tags on pages to reflect the page you're on  https://github.com/madisonsinc97/GDMA-2662-Assignment-1/blob/b543dbe1dfdda320b6c237bff24351d72c3e9e13/benefits.html#L13

On " be sure href values are spelled correctly to match the content" I keep double checking and I can't find anything wrong with my spelling and the contents. Could you let me know what I'm missing? it's Email: <a href=info@action.com>, right?

**Comment by madisonsinc97** [comment]
Sorry, I wrote the href I had and it turned it into a link. I have mailto:info@action.com
